name: Daily Auto Commit

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual run

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Auto Commit
      run: |
        echo "$(date)" >> log.txt
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add log.txt
        git commit -m "Daily commit - $(date) [skip ci]"
        git push
